### ISSUE TITLE
Is ActiveGS Active?

### ISSUE THREAD

**Issue by eduo** [ogoguel/activegs-ios#14]
There's been years without updates and no releases are displayed.

Not demanding anything, just asking. Maybe the repository moved in the past years and I can only find this one.

**Comment by yoshisuga** [comment]
This is the only repo but there hasn't been much activity.  It's still very much functional and the easier way of emulating an Apple IIGS. The other way is to do it through [MAME on iOS](https://github.com/yoshisuga/MAME4iOS) (I've gotten it to sort of work there).

I've been tinkering with ActiveGS occasionally [on my own fork](https://github.com/yoshisuga/activegs-ios/tree/remap_controls), where I added modern iPhone screen support, a custom keyboard and debugger written in Swift.

I was thinking of eventually making a PR for some of these changes.

**Comment by yoshisuga** [comment]
Sure, I made an IPA release on my fork:
https://github.com/yoshisuga/activegs-ios/releases/tag/2021.9

**Comment by eduo** [comment]
Thank you! It works a treat!

**Comment by ogoguel** [comment]
Not very active but at least trying to be sure it keeps compiling and running after each major iOS release!
