### ISSUE TITLE
Multiple Disk Drives

### ISSUE THREAD

**Issue by OzCapital** [ogoguel/activegs-ios#16]
I have recently downloaded and built the ActiveGS app. I’m interested in knowing whether the code supports apple 2 programs that utilise more than one disk. I can see from the code that multiple disks appear to be mounted when the software file names have the same prefix and the boot disk file name contains the string “disk1”. When you boot “disk1” you can see a disk icon appear in the top right hand corner that allows you to see all the disks with the same prefix.

This seems to allow me to swap disk1 for any other disk with the same prefix… but I need is to be able to do is place the second disk in disk drive 2. I note the WIN version of ActiveGS allows me to mount disk1 and disk2 images in different slots and allowing both disks to be “online”. 

Is the IOS version of ActiveGS meant to allow for two disks to be both “online” and each to be in its own disk drive? Am I just not seeing whether this can be done or is it not coded to do this?

Thanks.

**Comment by pacpir** [comment]
Adam:

I know the windows and the mac version allows for more than one disk to be
mounted.
The IOS version is a little trickier to use.  I would like to hear any
feedback from the others in the thread as well.

Perry

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ogoguel** [comment]
The iOS version supports the same multidisk mecanism than the desktop version.
You can mount multiple images on multiple disks (as in King's Quest GS)

```
<image slot="5" disk="1" icon="">http://www.virtualapple.org/gs/KingsQuest(1987)(Sierra)(Disk1of2).zip</image>
<image slot="5" disk="2" icon="">http://www.virtualapple.org/gs/KingsQuest(1987)(Sierra)(Disk2of2).zip</image>

```

or multiple images to be mounted on the same disk (as in King's Quest)

```
<image slot="6" disk="1" icon="">http://www.virtualapple.org/apple2/KingsQuest(A)(Disk1of4).zip</image>
<image slot="6" disk="1" icon="">http://www.virtualapple.org/apple2/KingsQuest(B)(Disk2of4).zip</image>
<image slot="6" disk="1" icon="">http://www.virtualapple.org/apple2/KingsQuest(C)(Disk3of4).zip</image>
 <image slot="6" disk="1" icon="">http://www.virtualapple.org/apple2/KingsQuest(Save)(Disk4of4).zip</image>
```

In that later case, a spinning disk  image will appear on the top left on the screen to let you change at anytime which image you would like to mount. Unfortunately, the UI color is a bit broken, but the mount button should work.

Hope it clarifies.

**Comment by OzCapital** [comment]
Thank you, this is very helpful information. You have confirm the functionality is there. I have discovered it is difficult to configure a 2 disk program (slot 6) that use both disk1 and disk2 when adding them to favourites. Having multiple disks in disk1 works just fine though. The code assumes “disk1” for multiple disks for slot 6.
