### ISSUE TITLE
Flip disk to the play side

### ISSUE THREAD

**Issue by tpitman** [ogoguel/activegs-ios#19]
I am trying to run Sundog on the emulator on an iPad.

I built activegs-ios and it works! That is great.

I have both disk images added to the default package and Sundog loads.

I have tried putting disk 1 in slot 6, drive 1 and disk 2 in drive 2.

I have tried just putting disk 1 in slot 6 and then making sure the names of the disks are the same with a Disk 1 and Disk 2 in the names.

When it gets to a certain point, however, it asks me to flip the disk to the play side.

I am not sure how to make that happen. Please advise....

**Comment by OzCapital** [comment]
You might like to have a read of closed issue #16 - Multiple Disk Drives. This might help, but please advise if it doesn’t.

**Comment by tpitman** [comment]
That works! The trick was putting in the same slot and disk #. That was not obvious from any of the other examples in the file.

Thank you! Now I can play my favorite game of all time on my iPad.
